# Generated by Django 3.0.3 on 2020-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepdetective', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quickshow', models.CharField(blank=True, max_length=100, null=True)),
                ('fakemark', models.CharField(max_length=5)),
                ('fakemarktext', models.CharField(max_length=20)),
                ('checkcontenttext', models.TextField()),
                ('checkcontentwriter', models.CharField(max_length=45)),
                ('checkcontecttype', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questiontext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlcontext', models.TextField()),
            ],
            options={
                'db_table': 'questiontext',
                'managed': False,
            },
        ),
    ]
